import lodash from 'lodash';

export const subColors = {
  BLUE: '#007AFF',
  BLUE_DARK: '#0056B4',
  BLUE_TOUCHED: '#0056B4',
  BLUE_LIGHT: '#BDDBFF',
  BLUE_DISABLED: '#BDDBFF',
  PURPLE: '#5551FF',
  PURPLE_DARK: '#3532B9',
  PURPLE_TOUCHED: '#3532B9',
  PURPLE_LIGHT: '#C8C7FF',
  PURPLE_DISABLED: '#C8C7FF',
  LAVENDER: '#CA5CFE',
  LAVENDER_DARK: '#953BC0',
  LAVENDER_TOUCHED: '#953BC0',
  LAVENDER_LIGHT: '#EECAFF',
  LAVENDER_DISABLED: '#EECAFF',
  CARROT: '#EB694C',
  CARROT_DARK: '#CA4E33',
  CARROT_TOUCHED: '#CA4E33',
  CARROT_LIGHT: '#FFBDAE',
  CARROT_DISABLED: '#FFBDAE',
  MUSTARD: '#F4C82A',
  MUSTARD_DARK: '#C5A121',
  MUSTARD_TOUCHED: '#C5A121',
  MUSTARD_LIGHT: '#FFEC9D',
  MUSTARD_DISABLED: '#FFEC9D',
  BROWN: '#CA8B2D',
  BROWN_DARK: '#99681F',
  BROWN_TOUCHED: '#99681F',
  BROWN_LIGHT: '#FFDFB0',
  BROWN_DISALBED: '#FFDFB0',
};

export const subColorMap = lodash.invert(subColors);

export type SubColorKey = keyof typeof subColors;
