# This is a basic workflow to help you get started with Actions

name: PR Test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn test:cov
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
