# This is a basic workflow to help you get started with Actions

name: PR Test

on:
  pull_request:
    branches:
      - master
      - develop


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: run test
        run: |
          cd src
          yarn install
          yarn test
